{
  "build": {
    "merge-install": true,
    "event-handlers": [
      "console_package_list+",
      "console_cohesion+",
    ],
    "cmake-args": [
      "-GNinja",
      "--no-warn-unused-cli",
      "-DCMAKE_BUILD_TYPE=Release",
      "-DCMAKE_C_COMPILER_LAUNCHER=buildcache",
      "-DCMAKE_CXX_COMPILER_LAUNCHER=buildcache",
      "-DINSTALL_EXAMPLES=OFF",
      "-DSECURITY=ON",
      "-DAPPEND_PROJECT_NAME_TO_INCLUDEDIR=ON",
    ],
    "executor": "sequential",
  },
  "test": {
    "merge-install": true,
    "event-handlers": [
      "console_cohesion+",
    ],
    "executor": "sequential",
  }
}
