name: ros-ws
channels:
  - conda-forge
dependencies:
  # Build tools
  - catkin_pkg
  - cmake
  - colcon-common-extensions
  - compilers
  - git
  - lark
  - make
  - ninja
  - pkg-config
  - pytest
  - vcstool
