name: ros-ws
channels:
  - conda-forge
dependencies:
  - asio
  - benchmark
  - bullet
  - eigen
  - freetype
  - freeimage
  - opencv
  - openexr=2.5.5
  - pybind11
  - pyqt5-sip
  - pyside2
  - qt-main
  - tinyxml
  - tinyxml2
  - pugixml
  - zlib
  - zziplib
  - sdl2
  - numpy
  - swig
  - sip
