name: ros-ws
channels:
  - conda-forge
dependencies:
  - asio
  - benchmark
  - eigen
  - freetype
  - freeimage
  - openexr
  - pybind11
  - pyqt5-sip
  - qt-main
  - tinyxml
  - tinyxml2
  - pugixml
  - zlib
  - zziplib
  - sdl2
  - numpy
  - swig
